<?php
	
	if (basename($_SERVER['PHP_SELF']) == basename(__FILE__)) 
	{ die('Error. No direct access allowed'); };
	
	$apps['rhythms'] = array(
		
		'date' => '2014-12-15',
		'name' => 'Tearfund Rhythms',
		'slug' => 'rhythms',
		'day_no' => '1',
		
		'url'  => 'http://rhythms.org/',
		'ios'  => 'https://itunes.apple.com/gb/app/rhythms-by-tearfund/id540674974?mt=8',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.tearfund.rhythmsbytearfund',
		
		'screenshots' => array(
			"day1-1.jpg",
			"day1-2.jpg",
			"day1-3.jpg",
			"day1-4.jpg"	
		),
		
		'content' => array(
			"There’s more to a to-do list than simply reeling off things that we could be doing.  There’s even more to thinking about your to-do list in a charitable way.  We should be thinking about what we’re spending our time doing in a Christ-centred way.  Rhythms has a basic mission statement.  It wants to change the way you live, and it wants to do it in a way that’s inspired by Jesus and in a church community.  It’s that community which is the heart and soul of the Rhythms experience.  They care about injustice in the world, and they want to make a difference.",
			"Rhythms provides a to-do list that isn’t about letting you remind yourself that you want to learn to play the guitar or take up wood carving.  It tells you about things that really need solving.  Problems that a community together can solve.  You can get a notification that reminds the whole Rhythm community to help clean your church this week.  Or gets thousands of people inviting a homeless person into church for a hot drink and a meal. Togetherness, generosity, caring - these are all aspects that are a key part of the Rhythm experience.  It can help you improve what you do for others - and all in a Christ centred way, surrounded and supported by other Christians."
		),
		
		'teaser' => 'Change the world through small, but regular, actions.',
				
		'quote' => array(
			'body' => 'So cool! An amazing way to put your faith into action... Quality app and a quality cause.',
			'cite_name' => 'Andy Eyre',
			'cite_desc' => 'Android user, Google Play Store reviewer',
			'cite_link' => 'https://play.google.com/store/apps/details?id=com.tearfund.rhythmsbytearfund&reviewId=Z3A6QU9xcFRPRTVqbWVxay1iYmdXMHRjSUJPTDc3Qm4xSTRqOFRFVmozZnlPZm5UaEE1MzdkNF9MX0RHOElQYWZ6WXdlLVNVc1YxSm9fQnBuQ0V0RnFBUFRB',
			'cite_avatar' => 'ae.jpg',
		),
	);
	
	
	$apps['got-questions'] = array(
		
		'date' => '2014-12-16',
		'name' => 'Got Questions?',
		'slug' => 'got-questions',
		'day_no' => '2',
		
		'url'  => 'http://www.gotquestions.org/',
		'ios'  => 'http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=366553550&mt=8',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.gotquestions.gqandapp&hl=en',
		'wmob' => 'http://www.windowsphone.com/s?appid=bb02838b-7e99-442f-b8a2-8e3caa09b1ee',
		
		'screenshots' => array(
			"day2-1.jpg",
			"day2-2.jpg",
			"day2-3.jpg",
			"day2-4.jpg"	
		),
		
		'content' => array(
			"All of us have questions about the Bible and Christianity.  There’s so much to know, and we’re always growing and learning throughout our lives.  As we get older we should be maturing in faith, but even with a few years of experience it’s still the common questions that often get us to trip up.  Sometimes, we just can’t recall the answer to that question, and wish that we had an easy way to find out in the moment.  Whilst that’s usually what our pastor or church leader is there for, sometimes it’s nice just to get a quick answer right there and then.  And that’s where Got Questions? comes in.",
			"Got Questions? has over four thousand of the most frequently asked questions about the Bible.  It’s organised by topic and includes a built-in search function, the ability to select favorite articles for easier future access, the capability to download new articles, and the option to ask a question directly if the answer to your question is not already available in the app. It’s easy to use, has an impressively wide range of subjects to browse and provides sound answers to get you thinking.   Get answers with Got Questions? right when you want them."
		),
		
		'teaser' => 'Get answers to the big questions that always bugged you.'
		/*
		
		'quote' => array(
			'body' => 'I say it without hyperbole: PrayerMate revitalized my prayer life.',
			'cite_name' => 'Tim Challies',
			'cite_desc' => 'Blogger, Author, and Book Reviewer',
			'cite_link' => 'http://www.challies.com/resources/how-an-app-revitalized-my-prayer-life',
			'cite_avatar' => 'tc.jpg',
		),
		*/
		
	);
	
	$apps['righteous-tales'] = array(
		
		'date' => '2014-12-17',
		'name' => 'Righteous Tales: David vs Goliath',
		'slug' => 'righteous-tales',
		'day_no' => '3',
		
		'url'  => 'http://righteoustales.com/david-vs.-goliath.html',
		'ios'  => 'http://itunes.apple.com/app/id763218550',
		
		'screenshots' => array(
			"day3-1.jpg",
			"day3-2.jpg",
			"day3-3.jpg",
			"day3-4.jpg"	
		),
		
		'content' => array(
			"Who doesn’t know the age old story of David and Goliath?  The brave, rugged shepherd boy with his sling and the stones from the brook, facing down the terrifying warrior from the Philistine ranks and overcoming! Now, you can bring that story to life for your kids with this interactive game.  Tap, tilt and swing through the levels and learn about the life of David and his epic showdown with the Philistine Giant!  With rich detail, immersive stories and sound presentation of Biblical values, this is great educational fun about one of the Bible’s greatest heroes.",
			"This is the account of one of the most famous moments in the great King David’s life.  His story has many ups and downs, but this moment shows his courage, preparation and great faith in God as he overcame a challenge that the entire Israelite army was too scared to face up to.  God has a plan for each of us, and - although we’re not likely to have to slay a terrible giant - it is never too early to learn that trust in God will bring us through even the darkest days."
		),
		
		'teaser' => 'Bring the biblical account of David and Goliath to life for your kids with this interactive game.',
		
		
		'quote' => array(
			'body' => '...I let my 6 year old daughter give it a test run... She loved it and when it was my turn she actually took the iPad out of my hand so that she could show me how to play!',
			'cite_name' => 'Jerry @ Relevant Gaming',
			'cite_desc' => 'Children\'s Pastor and the founder of Relevant Gaming',
			'cite_link' => 'http://relevant-gaming.com/david-vs-goliath-a-righteous-tale-review/',
			'cite_avatar' => 'jrg.jpg',
		),
		
		
	);
	
	$apps['covenant-eyes'] = array(
		
		'date' => '2014-12-18',
		'name' => 'Covenant Eyes',
		'slug' => 'covenant-eyes',
		'day_no' => '7',
		
		'url'  => 'http://www.covenanteyes.com/',
		'ios'  => 'http://itunes.apple.com/us/app/covenant-eyes/id335318146?mt=8',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.covenanteyes.androidservice',
		//'wmob' => '',

		'screenshots' => array(
			"day7-1.jpg",
			"day7-2.jpg",
			"day7-3.jpg",
			"day7-4.jpg"	
		),
		
		'content' => array(
			"",
		),
		
		'teaser' => '',
		
			'quote' => array(
				'body' => 'I’ve used different methods of Internet accountability for the past decade, and in my experience there’s not a better single tool than Covenant Eyes software.',
				'cite_name' => 'Joe Tyrpak',
				'cite_desc' => 'Pastor at Tri-County Bible Church, Madison',
				'cite_link' => 'http://andynaselli.com/covenant-eyes',
				'cite_avatar' => 'jt.jpg',
			),
		
	);
	
	$apps['explore'] = array(
		
		'date' => '2014-12-19',
		'name' => 'Explore',
		'slug' => 'explore',
		'day_no' => '4',
		
		'url'  => 'http://www.thegoodbook.co.uk/bible/daily-bible-reading/explore/explore-app',
		'ios'  => 'http://itunes.apple.com/us/app/explore-bible-devotional/id482034447',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.thegoodbook.explore',
		//'wmob' => '',

		'screenshots' => array(
			"day4-1.jpg",
			"day4-2.jpg",
			"day4-3.jpg",
			"day4-4.jpg"	
		),
		
		'content' => array(
			"Habitual reading of the bible is incredibly important for a healthy Christian life, a regular quiet time with the Lord will greatly help you as you grow in spiritual maturity. There are many sets of bible reading notes to help you engage with scripture, but what happens when you reach the end of the booklet? This time, why don’t you try one that’s delivered directly to your smartphone, for easy access at any time?",
			"It’ll start you out with 28 days of full devotionals, and then provide you with daily readings, questions to get you thinking and ideas for further contemplation, prayer and application in your life.  You can download books of the bible to go though in this fashion (some are still being added) and start - or restart - a time of close communion with the Lord as you study his word and think on what it says. However busy your life is, there’s always a place in your day when you can sit down and concentrate on matters more important that the hustle and bustle of day to day living.   With Explore, you possess a wonderful tool for studying God’s word, wherever, whenever.",
		),
		
		'teaser' => 'Make exploring God\'s word everyday the priority in your life.',
		
		/*
			'quote' => array(
				'body' => '...I let my 6 year old daughter give it a test run... She loved it and when it was my turn she actually took the iPad out of my hand so that she could show me how to play!',
				'cite_name' => 'Jerry @ Relevant Gaming',
				'cite_desc' => 'Children\'s Pastor and the founder of Relevant Gaming',
				'cite_link' => 'http://relevant-gaming.com/david-vs-goliath-a-righteous-tale-review/',
				'cite_avatar' => 'jrg.jpg',
			),
		*/
		
	);
	
	
	$apps['youversion'] = array(
		
		'date' => '2014-12-20',
		'name' => 'YouVersion',
		'slug' => 'youversion',
		'day_no' => '6',
		
		'url'  => 'https://www.youversion.com/apps',
		'ios'  => 'https://bible.com/app/ios',
		'droid'=> 'https://bible.com/app/android',
		'wmob' => 'https://bible.com/app/windowsphone',

		
		'screenshots' => array(
			"day6-1.jpg",
			"day6-2.jpg",
			"day6-3.jpg",
			"day6-4.jpg"	
		),
		
		'content' => array(
			"",
		),
		
		'teaser' => '',
		
		'quote' => array(
			'body' => 'For millions of readers around the world, [the] wildly successful free Bible app, YouVersion, is changing how, where and when they read the Bible.',
			'cite_name' => 'Amy O\'Leary',
			'cite_desc' => 'New York Times Deputy International Editor',
			'cite_link' => 'http://www.nytimes.com/2013/07/27/technology/the-faithful-embrace-youversion-a-bible-app.html',
			'cite_avatar' => 'al.jpg',
		),
		
	);
	
	
	$apps['union'] = array(
		
		'date' => '2014-12-21',
		'name' => 'Union',
		'slug' => 'union',
		'day_no' => '8',
		
		'url'  => 'http://www.uniontheology.org/',
		'ios'  => 'https://itunes.apple.com/us/app/union-theology/id945527935?mt=8&uo=4',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.subsplash.thechurchapp.s_738H67',
		//'wmob' => '',

		
		'screenshots' => array(
			"day8-1.jpg",
			"day8-2.jpg",
			"day8-3.jpg",
			"day8-4.jpg"	
		),
		
		'content' => array(
			"",
		),
		
		'teaser' => '',
		
		/*
			'quote' => array(
				'body' => '...I let my 6 year old daughter give it a test run... She loved it and when it was my turn she actually took the iPad out of my hand so that she could show me how to play!',
				'cite_name' => 'Jerry @ Relevant Gaming',
				'cite_desc' => 'Children\'s Pastor and the founder of Relevant Gaming',
				'cite_link' => 'http://relevant-gaming.com/david-vs-goliath-a-righteous-tale-review/',
				'cite_avatar' => 'jrg.jpg',
			),
		*/
		
	);
	
	
	$apps['lepton'] = array(
		
		'date' => '2014-12-22',
		'name' => 'Lepton',
		'slug' => 'lepton',
		'day_no' => '5',
		
		'url'  => 'https://lepton.co/',
		'ios'  => 'https://itunes.apple.com/us/app/id779651798',
		//'droid'=> '',
		//'wmob' => '',

		'screenshots' => array(
			"day5-1.jpg",
			"day5-2.jpg",
			"day5-3.jpg",
			"day5-4.jpg"	
		),
		
		'content' => array(
			"Christians should be generous with what they have.  We give to support local churches, fund church plants, support missionaries overseas and provide for many causes around the world.  But it’s not always easy to keep up to date with the situations of need around the world, and sometimes they fall under our radar.  Lepton is here to help.  It’s here to help you get organised with your giving.  To provide you with a simple way to find needy people, churches, ministries and other scenarios where your support could make all the difference.",
			"From funding a mission trip to Kenya to getting a church plant going in France, it’s all there at your fingertips.  And there’s no need to give wedges of money all at once, leaving you with a scramble to sort out your monthly finances.  With thousands of people around the world donating a few pounds here and there, the target is soon reached and the work of the gospel spread.  Lepton states that it believes the best way to grow in generosity is to give a little often. Sign up for it today, and become more generous than you had thought you could be.",
		),
		
		'teaser' => 'Be generous with a small amount to help the gospel spread.',
		
		'quote' => array(
			'body' => 'Rupert Edwards (Lepton founder) wants to change the way churches leverage technology in the areas of giving and prayer.',
			'cite_name' => 'Shamichael Hallman',
			'cite_desc' => 'Campus Pastor at New Direction Christian Church in Memphis, TN',
			'cite_link' => 'http://leadnet.org/code-for-the-kingdom-brad-russell-faithvillage/',
			'cite_avatar' => 'sh.jpg',
		),
	);
	
	
	
		
	$apps['fighter-verse'] = array(
		
		'date' => '2014-12-23',
		'name' => 'Fighter Verse',
		'slug' => 'fighter-verse',
		'day_no' => '9',
		
		'url'  => 'http://fighterverses.com/',
		'ios'  => 'https://itunes.apple.com/us/app/fighter-verses/id411711646?mt=8',
		'droid'=> 'https://play.google.com/store/apps/details?id=com.fighterverses.android',
		//'wmob' => '',

		
		'screenshots' => array(
			"day9-1.jpg",
			"day9-2.jpg",
			"day9-3.jpg",
			"day9-4.jpg"	
		),
		
		'content' => array(
			"All Christians are engaged in spiritual battle again the devil and his associates. Prepare yourself with the armour of the spirit. Grasp firmly in both hands the double edged sword of the word and store the words on your heart. Fighter Verses is an application that brings you an easy method for memorising God’s word.  Whether you stick with the inbuilt 520 key verses from scripture or add your own to learn, Fighter Verses will help you commit them to memory and boost your knowledge of scripture.",
			"Designed for everybody from children through to entire churches (and including seven bible translations and five quizzes) this app is a great way to help you and those around you get to know the bible better.  With a full five year plan included and a handy reviewing system to make sure the verses stay with you, Fighter Verses is committed to the task of keeping Christians firmly equipped to fight the good fight of faith as they struggle on through their daily life.",
		),
		
		'teaser' => 'Commit God\'s word to your memory, and your heart',
		
		'quote' => array(
			'body' => 'I\'m excited about the Fighter Verse App... This is going to be with me every day.',
			'cite_name' => 'John Piper',
			'cite_desc' => 'founder and teacher of desiringGod.org and chancellor of Bethlehem College & Seminary',
			'cite_link' => 'http://www.desiringgod.org/blog/posts/fighter-verses-on-your-iphone-or-android',
			'cite_avatar' => 'jp.jpg',
		),
		
		
	);
	
	$apps['prayermate'] = array(
		'date' => '2014-12-24',
		'name' => 'PrayerMate',
		'slug' => 'prayermate',
		'day_no' => '10',
		
		'url'  => 'http://app.prayermate.net',
		'ios'  => 'http://itunes.apple.com/us/app/prayermate-quiet-time-organiser/id434815549?mt=8&ls=1',
		'droid'=> 'https://play.google.com/store/apps/details?id=net.geero.prayermate',
		
		'video' => '<iframe width="560" height="315" src="//www.youtube.com/embed/Y2UCcjs1kV8" frameborder="0" allowfullscreen></iframe>',
		
		'screenshots' => array(
			"day10-1.png",
			"day10-2.png",
			"day10-3.png",
			"day10-4.png"	
		),
		
		'content' => array(
			"A Christian’s prayer life can be one of the toughest things we do. We’re slow to remember what we should be thinking of, bad at remembering all those prayer requests and often so distracted by other thoughts to that spending a focused time in prayer becomes virtually impossible.",
			"PrayerMate is a straightforward tool that helps you get organised in your prayer life. It allows you to enter your own prayer points, as well as providing a means to access requests from others - such as Operation World - neatly categorised to suit the way that you pray. When you open up Prayer Mate, a selection of your prayer requests are shown one at a time on cards, allowing you to pray for each subject individually. You can schedule cards by the time and date or simply let the app choose for you. It’s simple to understand, the interface is easy on the eye to look at and intuitive to use, even for those unfamiliar with apps.",
			"Finding time to pray is a real issue for many people in today’s busy world. It’s tough to find the time to set apart, and harder still to remember when that was. PrayerMate is a way to help you with this. It supports you as you try and find the time to spend in prayer, remembers those things that you forgot and presents you with the tools to easily locate subjects outside of your immediate experience to remember in your prayers."
		),
		
		'teaser' => 'Struggling with prayer?  PrayerMate is a helpful tool to get you back on track.',
		
		'quote' => array(
			'body' => 'I say it without hyperbole: PrayerMate revitalized my prayer life.',
			'cite_name' => 'Tim Challies',
			'cite_desc' => 'Blogger, Author, and Book Reviewer',
			'cite_link' => 'http://www.challies.com/resources/how-an-app-revitalized-my-prayer-life',
			'cite_avatar' => 'tc.jpg',
		),
	);