<?php
	
	if (basename($_SERVER['PHP_SELF']) == basename(__FILE__)) 
	{ die('Error. No direct access allowed'); };
	
	$apps[] = array(
		
		'date' => '2014-12-15',
		'name' => 'Tearfund Rhythms'
		
	);
	
	
	$apps[] = array(
		
		'date' => '2014-12-16',
		'name' => 'Got Questions?'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-17',
		'name' => 'Righteous Tales'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-18',
		'name' => 'Solid Joys'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-19',
		'name' => 'Lepton'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-20',
		'name' => 'YouVersion'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-21',
		'name' => 'Covenant Eyes'
		
	);
	
	$apps[] = array(
		
		'date' => '2014-12-22',
		'name' => 'Heroes'
		
	);
	
	$apps['fighter-verse'] = array(
		
		'date' => '2014-12-23',
		'name' => 'Fighter Verse',
		'slug' => 'fighter-verse'
	);
	
	$apps['prayermate'] = array(
		
		'date' => '2014-12-24',
		'name' => 'PrayerMate',
		'slug' => 'prayermate',
		
	);